### ISSUE TITLE
commandlineplugin, echo, single quotes... confused

### ISSUE THREAD

**Issue by pr3sidentspence** [n8henrie/fauxmo-plugins#2]
I've done this before, but the SD card on my pi got corrupted, and guess who didn't make a backup of his configs. Anyway...

I'm trying to send commands to mochad to control x10 switches. I need to echo text to nc. I can manually run:
```
echo 'rf a1 on' | nc localhost 1099
```
...and it works.

I've put the following in my config.json:
```
"on_cmd": "echo 'rf a4 on' | nc localhost 1099",
```
...and it doesn't work. Alexa reports, "OK," but the lights do not change. Looking at the status of my fauxmo service, I see:
```
Aug 02 22:32:01 autopi fauxmo[6055]: rf a1 on | nc localhost 1099
```
Which is... confusing. If this is the result of the echo (it seems to be as the touch example doesn't put anything in the status), then why is it not just rf a1 on?  If it's ignoring the single quotes, then why is it echoing anything at all?

I monitored mochad by running nc, but nothing goes to it. I also usually get alerts when mochad executes a command, but did not see any.

**Comment by n8henrie** [comment]
I've never heard of mochad, looks like some kind of RF controller? Probably not relevant.

Kind of looks like fauxmo is `echo`ing the whole rest of the line: `'rf a4 on' | nc localhost 1099"`.

In the future, please try to [read through the docstrings](https://github.com/n8henrie/fauxmo-plugins/blob/bac591cc1fa77f7fda05bc0febbb54f04478e625/commandlineplugin.py#L17) before filing an issue:

> Note that `subprocess.run` as implemented in this plugin doesn't handle complex
commands with pipes, redirection, or multiple statements joined by `&&`, `||`,
`;`, etc., so you can't just use e.g. `"command that sometimes fails || true"`
to avoid the delay and Alexa's response. If you really want to handle more
complex commands, consider using this plugin as a template for another one
using `os.system` instead of `subprocess.run`, but realize that this comes with
substantial security risks that exceed my ability to explain.

My recommendation for an easier fix would be to put the `echo 'rf a4 on' | nc localhost 1099` into a shell script, e.g.

```bash
#! /bin/bash
# testfile.sh
echo 'rf a4 on' | nc localhost 1099
```

Make it executable (`chmod +x testfile.sh`) and test that it works directly (`./testfile.sh`), and if so then see if you can just call that from commandlineplugin.

**Comment by pr3sidentspence** [comment]
Weird, I totally read that paragraph (I remember the end of it), but I must have been half asleep to miss that. I even did 15 minutes of research into whether Shlex was mishandling quotes. Sorry about that.

And, I think what you suggested is exactly what I must have done last time. Thanks!

**Comment by pr3sidentspence** [comment]
PS - Is there a place to ask questions or for help with this, or any project, without filing an issue? I'm a github neophyte.

**Comment by n8henrie** [comment]
It depends on the organization -- many have a chatroom like Gitter, Slack, or IRC that can work for informal stuff. I can field really quick Qs from Twitter, but otherwise an issue is appropriate.
